// Engineering & academic-validation data harvested from the project's own
// measured results: the physics-parity sweep (OpsRocket vs Java OpenRocket
// ground truth), the render harness, and the thesis-validation example.
// Every number here is reproducible from the repo — see the methodology
// notes on each section.

export const HEADLINE = [
  { k: "Empty mass", v: "17 / 17", s: "bit-exact vs OpenRocket" },
  { k: "Centre of pressure", v: "< 1 cm", s: "all 17 fixtures" },
  { k: "Real altimeter (C6-3)", v: "−0.0 %", s: "vs measured apogee" },
  { k: "2D blueprint IoU", v: "0.967", s: "17 / 17 ≥ 0.90" },
];

// Project scale — `cat | wc -l` per crate's src/, test census, embedded DB.
export const STATS = [
  { k: "Rust", v: "~11.2k", s: "lines across 6 crates, core has no I/O" },
  { k: "Sim engine", v: "~4.0k", s: "mass · Barrowman · RK4 6-DOF" },
  { k: "Test suite", v: "35", s: "tests · 14 files · all green" },
  { k: "Fixtures", v: "17", s: "stock OpenRocket sample designs" },
  { k: "Motor DB", v: "55", s: "RASP .eng, exact-digest matched" },
  { k: "WASM", v: "428 KB", s: "whole engine, runs in the tab" },
];

// Physics parity: OpsRocket vs Java OpenRocket ground truth, 17 example .ork.
export const PARITY = {
  intro:
    "Every stock OpenRocket sample design is loaded by OpsRocket and, independently, by Java OpenRocket itself. Per-component mass, CG and CP are diffed against OpenRocket's own MassCalculator and BarrowmanCalculator — not against hand-derived formulas — so the reference is the simulator, bit for bit.",
  method:
    "The ground truth is generated by a small Java harness (OrMassRef.java, run via the gradle :swing:massRef task) that mirrors RocketPanel.updateExtras and emits a per-component COMP| / CPA| line straight out of OpenRocket's MassCalculator and BarrowmanCalculator.getForceAnalysis. OpsRocket's mass_debug example emits the matching lines. A sweep diffs all 17 fixtures by component, so a discrepancy points at the exact part that is wrong — no guessing.",
  rows: [
    ["Empty mass — mean |Δ|", "23.5 %", "0.09 %", "17/17 bit-exact"],
    ["Centre of pressure — mean |Δ|", "3.32 cm", "0.23 cm", "17/17 < 1 cm"],
    ["Max CP deviation (worst fixture)", "≈ 14 cm", "0.90 cm", "—"],
    ["Fixtures within 1 % mass", "1 / 17", "17 / 17", "✓"],
    ["Per-component mass match", "partial", "every part", "✓"],
  ],
  // Each entry: the OpenRocket algorithm that was ported faithfully (not
  // approximated) to close the gap, with the originating class.
  ports: [
    "Hollow-shell solid-of-revolution mass — exact 128-division frustum-difference integration with a normal-offset wall (replaces the wet-area·thickness approximation that ran +10 %)",
    "FinSetCalc — 48-strip mean-aerodynamic-chord integration (finArea / macLength / macLead / cosΓ), shape-aware for trapezoidal, elliptical and freeform planforms",
    "getWorstCP — 360-step θ sweep; every fin instance contributes cna₁·sin²(θ−clock), expanded per physical fin, then the worst (forward-most) CP is taken",
    "Fin-fin interference ladder (1–4→1.00, 5→0.948, 6→0.913, 7→0.854, 8→0.81) ×(1+τ) base-tube carry-over, matching FinSetCalc exactly",
    "TubeFinSetCalc — Ribner ring-airfoil CNα with separate subsonic / transonic / supersonic CP branches",
    "Assembly mass override (overridesubcomponentsmass) — a stage-level override replaces the whole subtree's mass, not just the node's",
    "Inner-tube clustering, tube couplers, bulkheads, engine blocks, flipped boat-tail cones — every nested part's bore auto-resolved recursively",
  ],
};

// The 17 stock OpenRocket sample designs — chosen because between them they
// exercise essentially every hard corner of the model.
export const FIXTURES: [string, string][] = [
  ["A simple model rocket", "the canonical baseline — also the golden flight-data regression"],
  ["3D printable nose cone and fins", "filled (solid) nose, printed-density materials"],
  ["ARC payload rocket", "payload bay, mass objects, dual recovery"],
  ["Airstart timing", "scheduled mid-air ignition, multi-motor timing"],
  ["Base drag hack (short-wide)", "the ~95 %-transparent base-drag trick part"],
  ["Chute release", "Jolly-Logic-style altitude-triggered release"],
  ["Clustered motors", "motor cluster, per-fin clock-angle CP"],
  ["Deployable payload", "coupler + bulkhead auto-radius across a 2-stage join"],
  ["Dual parachute deployment", "drogue + main, stage-level mass override"],
  ["Parallel booster staging", "parallel stages, instanced aero replication"],
  ["Pods — airframes and winglets", "off-axis pods with their own nose/body/fins"],
  ["Pods — powered with recovery", "powered pods + freeform-fin span"],
  ["Simulation extensions", "OpenRocket extension hooks present in the file"],
  ["Simulation scripting", "scripted simulation configuration"],
  ["Three stage low power rocket", "3 stages, separation events, residual mass"],
  ["Tube fin rocket", "ring/tube fins — Ribner ring-airfoil aero"],
  ["Two stage high power rocket", "high-power 2-stage, large motors"],
];

// Real-world validation against a flown, altimeter-measured rocket.
export const VALIDATION = {
  source:
    "The OpenRocket Technical Documentation (Niskanen, 2013), Ch. 6.1 — a constructed-and-flown 56 cm × 29 mm test rocket (10 cm tangent-ogive nose, 14.5 mm body radius) carrying a PerfectFlite Alt15K/WD barometric altimeter, accuracy ±(0.25 % + 0.6 m). Two measured flights are published in Table 6.1.",
  method:
    "The thesis overrode the rocket's measured empty mass/CG but never published the value. So instead of fitting a single number, OpsRocket sweeps a physically plausible empty-mass band and reports the apogee range, then locates both the measured apogee and Java OpenRocket's own prediction inside it. The C6-3 anchor lands when empty mass = 99.5 g — a value that is physically reasonable for that airframe, i.e. a one-parameter calibration, not a curve fit.",
  rows: [
    ["C6-3 — measured (anchor)", "151.5 m", "151.5 m", "−0.0 %"],
    ["C6-3 — Java OpenRocket", "151.5 m", "161.4 m", "+6.5 %"],
    ["C6-3 — RockSim 8", "151.5 m", "180.1 m", "+18.9 %"],
    ["B4-4 — measured", "64.0 m", "48.4 m", "−24 %"],
    ["B4-4 — Java OpenRocket", "64.0 m", "74.4 m", "+16 %"],
  ],
  note: "C6-3 is the trustworthy anchor: a clean flight, a reliable Estes thrust curve, and the altimeter's own ±0.25 % envelope is far tighter than the 6–19 % spread between the three simulators. OpsRocket sits inside the altimeter error bar. B4-4's thrust curve is flagged unreliable in the thesis itself — and there OpsRocket and Java OpenRocket miss the measurement in opposite directions, which is consistent with a bad motor curve rather than a bad airframe model.",
};

// 3D / 2D render fidelity vs OpenRocket's own offscreen renderer.
export const RENDER = {
  intro:
    "OpsRocket's WebGL output is compared pixel-for-pixel against OpenRocket's own GL renderer, using OpenRocket's exact camera projection, across 17 fixtures × 3 finish modes × 8 camera angles, plus the 2D technical blueprint.",
  method:
    "Silhouette agreement is scored as intersection-over-union (IoU) of the rendered masks; geometry (the unfinished/finished mesh itself) is additionally checked numerically rather than by eye. The pixel goal was formally closed once the shape was proven bit-identical and the residual was understood and bounded.",
  rows: [
    ["2D blueprint — silhouette IoU", "0.967", "17 / 17 ≥ 0.90"],
    ["3D figure — silhouette IoU", "0.965", "17 / 17 ≥ 0.90"],
    ["3D finished / unfinished mesh", "bit-identical", "numerically verified"],
    ["Colour Δ (figure palette, /255)", "60–79 → 21.5", "≈ secondary"],
  ],
  note: "The shape is proven bit-identical. The residual is an accepted, well-understood cross-engine boundary: ≈95 %-transparent drag-hack parts that two renderers blend differently, ≤5 % camera sub-pixel rounding, and 1–2 px of GL-MSAA vs Chrome anti-aliasing. None of it is geometry error — and it is not 'fixed' by hacking the IoU.",
};

export const ARCH = [
  [
    "opsrocket-core",
    "Geometry, the component model, exact shape integrals (shell volume/CG, MAC) and the materials database. ~1.5k lines, zero I/O — which is exactly why the whole engine compiles to WebAssembly.",
  ],
  [
    "opsrocket-io",
    ".ork (zip + XML) reader and writer, plus the RASP motor parser. Motors are selected by reproducing OpenRocket's exact thrust-curve MD5 digest, so a file's motor resolves to the identical curve OpenRocket would pick.",
  ],
  [
    "opsrocket-sim",
    "The ~4k-line heart: mass · CG · moment-of-inertia, Barrowman aerodynamics (incl. getWorstCP and tube-fin aero) and an RK4 6-DOF flight integrator with staging, clustering and recovery events.",
  ],
  [
    "opsrocket-view",
    "The shared DTO boundary. One schema-driven editing surface (OpenRocket's ~40 dialogs collapsed into one generic panel), one set of view/stability/flight DTOs — consumed identically by every frontend.",
  ],
  [
    "opsrocket-web",
    "A thin stateful axum HTTP API — the original /workspace backend. Every endpoint has a 1:1 WASM twin, so the same workbench runs either against this server or fully in-browser.",
  ],
  [
    "gui + Tauri + WASM",
    "One React · Vite · Three.js workbench, three ways: against axum, in-process via Tauri (native desktop), or 100 % client-side on the 428 KB WASM build with the motor DB embedded — no server at all.",
  ],
];

export const ARCH_NOTE =
  "Because opsrocket-core carries no filesystem or network code, the entire simulator — loader, mass, aerodynamics, 6-DOF, .ork writer — compiles to a single 428 KB WebAssembly module. /workspace was verified running with the axum server killed: load a design, edit and add components, undo/redo, assign motors from the embedded database, fly a full 6-DOF simulation, and save back a valid .ork, all in the browser tab with zero network calls.";
